# fly.toml app configuration file generated for weatherpulse on 2025-08-05T21:49:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weatherpulse'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false       # <— Changed from 'stop' to false to disable scale-to-zero
  auto_start_machines = true
  min_machines_running = 1         # <— Changed from 0 to 1 to keep one machine always running
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
